package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, LOST, POISON, COPY, GET, ASK_ADD, ASK_REMOVE, SEND, REMOVE, PING, PONG, IS_ALIVE, ALIVE, SUS, TOK_REQ, TOK_SEND, TOK_REC, TOK_COMP
}
